#cloud-config

# Update system packages
package_update: true
package_upgrade: true

# Install required packages
packages:
  - curl
  - wget
  - git
  - docker.io
  - docker-compose

# Create application user
users:
  - name: livekit
    groups: [docker, sudo]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

# Write files
write_files:
  - path: /opt/livekit-voice-agent/docker-compose.yml
    content: |
      version: '3.8'
      
      services:
        livekit-server:
          image: livekit/livekit-server:latest
          ports:
            - "7880:7880"
            - "7881:7881"
            - "7882:7882/udp"
          command: --dev --bind 0.0.0.0
          environment:
            - LIVEKIT_KEYS=devkey: secret
          restart: unless-stopped
      
        voice-agent-api:
          build: .
          ports:
            - "8000:8000"
          environment:
            - LIVEKIT_URL=http://livekit-server:7880
            - LIVEKIT_API_KEY=devkey
            - LIVEKIT_API_SECRET=secret
            - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/service-account.json
            - GOOGLE_API_KEY=${GOOGLE_API_KEY}
            - SIP_OUTBOUND_TRUNK_ID=${SIP_OUTBOUND_TRUNK_ID}
            - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
            - CARTESIA_API_KEY=${CARTESIA_API_KEY}
            - CARTESIA_VOICE_ID=${CARTESIA_VOICE_ID}
            - PORT=8000
          volumes:
            - ./keys:/app/keys:ro
          depends_on:
            - livekit-server
          restart: unless-stopped
      
        voice-agent-worker:
          build: .
          command: python agent.py
          environment:
            - LIVEKIT_URL=http://livekit-server:7880
            - LIVEKIT_API_KEY=devkey
            - LIVEKIT_API_SECRET=secret
            - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/service-account.json
            - GOOGLE_API_KEY=${GOOGLE_API_KEY}
            - SIP_OUTBOUND_TRUNK_ID=${SIP_OUTBOUND_TRUNK_ID}
            - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
            - CARTESIA_API_KEY=${CARTESIA_API_KEY}
            - CARTESIA_VOICE_ID=${CARTESIA_VOICE_ID}
          volumes:
            - ./keys:/app/keys:ro
          depends_on:
            - livekit-server
          restart: unless-stopped

  - path: /opt/livekit-voice-agent/.env
    content: |
      # LiveKit server
      LIVEKIT_URL=http://localhost:7880
      LIVEKIT_API_KEY=devkey
      LIVEKIT_API_SECRET=secret
      
      # Google credentials (you'll need to upload your service account key)
      GOOGLE_APPLICATION_CREDENTIALS=/opt/livekit-voice-agent/keys/service-account.json
      GOOGLE_API_KEY=your-gemini-api-key
      
      # SIP configuration
      SIP_OUTBOUND_TRUNK_ID=your-sip-trunk-id
      
      # Optional: Deepgram/Cartesia keys
      DEEPGRAM_API_KEY=your-deepgram-key
      CARTESIA_API_KEY=your-cartesia-key
      CARTESIA_VOICE_ID=your-cartesia-voice-id

  - path: /etc/systemd/system/livekit-voice-agent.service
    content: |
      [Unit]
      Description=LiveKit Voice Agent
      Requires=docker.service
      After=docker.service
      
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/opt/livekit-voice-agent
      ExecStart=/usr/local/bin/docker-compose up -d
      ExecStop=/usr/local/bin/docker-compose down
      TimeoutStartSec=0
      
      [Install]
      WantedBy=multi-user.target

# Create directories
runcmd:
  - mkdir -p /opt/livekit-voice-agent/keys
  - chown -R livekit:livekit /opt/livekit-voice-agent
  - systemctl enable livekit-voice-agent.service
  - systemctl start livekit-voice-agent.service
