# Use environment variables from .env file
services:
  livekit-server:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    command: --dev --bind 0.0.0.0
    environment:
      LIVEKIT_KEYS: ${LIVEKIT_KEYS}
    restart: unless-stopped

  voice-agent-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
      - CARTESIA_VOICE_ID=${CARTESIA_VOICE_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - SIP_OUTBOUND_TRUNK_ID=${SIP_OUTBOUND_TRUNK_ID}
      - PORT=${PORT}
    volumes:
      - ./keys:/app/keys:ro
    depends_on:
      - livekit-server
    restart: unless-stopped

  voice-agent-worker:
    build: .
    command: python agent.py dev
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
      - CARTESIA_VOICE_ID=${CARTESIA_VOICE_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - SIP_OUTBOUND_TRUNK_ID=${SIP_OUTBOUND_TRUNK_ID}
    volumes:
      - ./keys:/app/keys:ro
    depends_on:
      - livekit-server
    restart: unless-stopped
